import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://tvtxwckassjcuelfmbme.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dHh3Y2thc3NqY3VlbGZtYm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ0NjUxMTgsImV4cCI6MjAzMDA0MTExOH0.wPb_yBNtnyuhxAjmJfOPYNIxZ_7n6xrSp6cWFYTbM1w')